/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package eremeykin.pete.abaqusscriptrunner;

import eremeykin.pete.coreapi.loggerapi.Logger;
import eremeykin.pete.coreapi.loggerapi.LoggerManager;
import eremeykin.pete.coreapi.workspace.WorkspaceManager;
import java.awt.Cursor;
import java.io.BufferedReader;
import java.io.File;
import java.io.IOException;
import java.io.InputStreamReader;
import static java.lang.Thread.sleep;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import org.openide.util.Exceptions;
import org.openide.util.NbPreferences;
import org.openide.windows.IOProvider;
import org.openide.windows.InputOutput;

final class AbaqusPanel extends javax.swing.JPanel {

    private StringBuffer lmgrdVersion = new StringBuffer();
    private StringBuffer abaqusVersion = new StringBuffer();
    private final String abaqusBat = "abaqus.bat";
    private final String lmgrdExe = "lmgrd.exe";
    private final AbaqusOptionsPanelController controller;
    private static final Logger LOGGER = LoggerManager.getLogger(WorkspaceManager.class);

    AbaqusPanel(AbaqusOptionsPanelController controller) {
        this.controller = controller;
        initComponents();
        // TODO listen to changes in form fields and call controller.changed()
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        org.openide.awt.Mnemonics.setLocalizedText(jLabel1, org.openide.util.NbBundle.getMessage(AbaqusPanel.class, "AbaqusPanel.jLabel1.text")); // NOI18N

        jTextField1.setText(org.openide.util.NbBundle.getMessage(AbaqusPanel.class, "AbaqusPanel.jTextField1.text")); // NOI18N

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        org.openide.awt.Mnemonics.setLocalizedText(jLabel2, org.openide.util.NbBundle.getMessage(AbaqusPanel.class, "AbaqusPanel.jLabel2.text")); // NOI18N

        jTextField2.setText(org.openide.util.NbBundle.getMessage(AbaqusPanel.class, "AbaqusPanel.jTextField2.text")); // NOI18N

        org.openide.awt.Mnemonics.setLocalizedText(jButton1, org.openide.util.NbBundle.getMessage(AbaqusPanel.class, "AbaqusPanel.jButton1.text")); // NOI18N
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        org.openide.awt.Mnemonics.setLocalizedText(jButton2, org.openide.util.NbBundle.getMessage(AbaqusPanel.class, "AbaqusPanel.jButton2.text")); // NOI18N
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/res/questionIcon.png"))); // NOI18N
        org.openide.awt.Mnemonics.setLocalizedText(jButton4, org.openide.util.NbBundle.getMessage(AbaqusPanel.class, "AbaqusPanel.jButton4.text")); // NOI18N
        jButton4.setBorder(null);
        jButton4.setBorderPainted(false);
        jButton4.setContentAreaFilled(false);
        jButton4.setMaximumSize(new java.awt.Dimension(23, 23));
        jButton4.setMinimumSize(new java.awt.Dimension(23, 23));
        jButton4.setPreferredSize(new java.awt.Dimension(23, 23));
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AbaqusCheckActionPerformed(evt);
            }
        });

        jButton5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/res/questionIcon.png"))); // NOI18N
        org.openide.awt.Mnemonics.setLocalizedText(jButton5, org.openide.util.NbBundle.getMessage(AbaqusPanel.class, "AbaqusPanel.jButton5.text")); // NOI18N
        jButton5.setBorder(null);
        jButton5.setBorderPainted(false);
        jButton5.setContentAreaFilled(false);
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LmgrdCheckActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTextField1, javax.swing.GroupLayout.DEFAULT_SIZE, 164, Short.MAX_VALUE)
                    .addComponent(jTextField2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButton5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton2))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton1)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel1)
                        .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jButton1, javax.swing.GroupLayout.Alignment.TRAILING))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel2)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jButton2))
                    .addComponent(jButton5))
                .addContainerGap(199, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        String windir = System.getenv("WINDIR").substring(0, 1) + ":\\";
        JFileChooser fileChooser = new JFileChooser(windir);
        fileChooser.setFileSelectionMode(JFileChooser.DIRECTORIES_ONLY);
        int result = fileChooser.showDialog(this, "OK");
        if (result == JFileChooser.APPROVE_OPTION) {
            File file = fileChooser.getSelectedFile();
            boolean containsAbaqus = false;
            if (file != null) {
                for (File f : file.listFiles()) {
                    if (f.getName().equals(abaqusBat)) {
                        containsAbaqus = true;
                        break;
                    }
                }
            }
            if (!containsAbaqus) {
                JOptionPane.showMessageDialog(this, "There is no \"" + abaqusBat + "\" in the selected directory!\nProbably it is wrong path.", "Wrong path", JOptionPane.ERROR_MESSAGE);
            }
            jTextField1.setText(file.getAbsolutePath());
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        String windir = System.getenv("WINDIR").substring(0, 1) + ":\\";
        JFileChooser fileChooser = new JFileChooser(windir);
        fileChooser.setFileSelectionMode(JFileChooser.FILES_ONLY);
        int result = fileChooser.showDialog(this, "OK");
        if (result == JFileChooser.APPROVE_OPTION) {
            File file = fileChooser.getSelectedFile();
            if (!file.getName().equals(lmgrdExe)) {
                JOptionPane.showMessageDialog(this, "The selected file name is not \"" + lmgrdExe + "\"!\nProbably it is wrong path.", "Wrong path", JOptionPane.ERROR_MESSAGE);
            }
            jTextField2.setText(file.getAbsolutePath());
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void AbaqusCheckActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AbaqusCheckActionPerformed
        abaqusVersion.setLength(0);
        try {
            this.setCursor(Cursor.getPredefinedCursor(Cursor.WAIT_CURSOR));
            try {
                String abaqusPath = jTextField1.getText();
                String[] args = {"whereami"};
                VersionChecker vChecker = new VersionChecker("abaqus", args, abaqusPath, "Abaqus ");
                abaqusVersion = vChecker.check();
            } catch (IOException ex) {
                Exceptions.printStackTrace(ex);
            } catch (InterruptedException ex) {
                Exceptions.printStackTrace(ex);
            }
        } finally {
            this.setCursor(null);
            if (abaqusVersion.length() > 0) {
                jButton4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/res/ok.png"))); // NOI18N
                JOptionPane.showMessageDialog(null, "Abaqus detected: " + abaqusVersion.toString(), "Abaqus detected", JOptionPane.INFORMATION_MESSAGE);
            } else {
                jButton4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/res/cross-icon.png"))); // NOI18N
                JOptionPane.showMessageDialog(null, "Abaqus not found!", "Abaqus not found", JOptionPane.ERROR_MESSAGE);
            }
        }
    }//GEN-LAST:event_AbaqusCheckActionPerformed

    private void LmgrdCheckActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LmgrdCheckActionPerformed
        lmgrdVersion.setLength(0);
        try {
            this.setCursor(Cursor.getPredefinedCursor(Cursor.WAIT_CURSOR));
            try {
                String lmgrdPath = jTextField2.getText();
                String[] args = {"-z","-v"};
                VersionChecker vChecker = new VersionChecker("lmgrd", args, lmgrdPath, "lmgrd v");
                lmgrdVersion = vChecker.check();
            } catch (IOException ex) {
                Exceptions.printStackTrace(ex);
            } catch (InterruptedException ex) {
                Exceptions.printStackTrace(ex);
            }
        } finally {
            this.setCursor(null);
            if (lmgrdVersion.length() > 0) {
                jButton5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/res/ok.png"))); // NOI18N
                JOptionPane.showMessageDialog(null, "lmgrd detected: " + lmgrdVersion.toString(), "Abaqus detected", JOptionPane.INFORMATION_MESSAGE);
            } else {
                jButton5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/res/cross-icon.png"))); // NOI18N
                JOptionPane.showMessageDialog(null, "\"lmgrd.exe\" not found!", "lmgrd not found", JOptionPane.ERROR_MESSAGE);
            }
        }

    }//GEN-LAST:event_LmgrdCheckActionPerformed

    void load() {
        String abaqusPath = NbPreferences.forModule(AbaqusPanel.class).get("ABAQUS_PATH", "");
        String lmgrdPath = NbPreferences.forModule(AbaqusPanel.class).get("LMGRD_PATH", "");
        jTextField1.setText(abaqusPath);
        jTextField2.setText(lmgrdPath);
    }

    void store() {
        NbPreferences.forModule(AbaqusPanel.class).put("ABAQUS_PATH", jTextField1.getText());
        NbPreferences.forModule(AbaqusPanel.class).put("LMGRD_PATH", jTextField2.getText());
    }

    boolean valid() {
        // TODO check whether form is consistent and complete
        return true;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    // End of variables declaration//GEN-END:variables
}
