package eremeykin.pete.viewport;

import com.sun.j3d.exp.swing.JCanvas3D;
import com.sun.j3d.utils.geometry.ColorCube;
import com.sun.j3d.utils.universe.SimpleUniverse;
import java.awt.Dimension;
import javax.media.j3d.BranchGroup;
import javax.media.j3d.Canvas3D;
import javax.media.j3d.GraphicsConfigTemplate3D;
import javax.media.j3d.PhysicalBody;
import javax.media.j3d.PhysicalEnvironment;
import javax.media.j3d.View;

/**
 *
 * @author cyguard
 */
public class JCanvas3D_test extends javax.swing.JFrame {

    /**
     * Creates new form JCanvas3D_test
     */
    public JCanvas3D_test() {
        initComponents();
// Scenegraph
//        BranchGroup bg = new BranchGroup();
//        ColorCube cube = new ColorCube(0.2f);
//        bg.addChild(cube);
//// JCanvas
//        JCanvas3D jCanvas = new JCanvas3D();
//        jCanvas.setResizeMode(JCanvas3D.RESIZE_IMMEDIATELY);
//        this.add("Center", jCanvas);
//        Dimension dim = new Dimension(100, 100);
//        jCanvas.setPreferredSize(dim);
//        jCanvas.setSize(dim);
////
//        Canvas3D c = jCanvas.getOffscreenCanvas3D();
//
//        SimpleUniverse u = new SimpleUniverse(c);
//        u.getViewingPlatform().setNominalViewingTransform();
//        u.addBranchGraph(bg);

//
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
//
    private void initComponents() {

//        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        java.awt.Dimension screenSize = java.awt.Toolkit.getDefaultToolkit().getScreenSize();
        setBounds((screenSize.width - 400) / 2, (screenSize.height - 300) / 2, 400, 300);
    }//

    /**
     * @param args the command line arguments
     */
    public static void main(String... args) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JCanvas3D_test().setVisible(true);
            }
        });
    }

// Variables declaration - do not modify
// End of variables declaration
}
